<section class="content-header">
    <h1>
        Categoria de Veículo
        <small>Acompanhe aqui as categorias de veículos cadastrados</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/veiculos">Veículos</a></li>
        <li class="active">Categoria de Veículo</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <div class="row">
                        <div class="col-md-6">
                            <a href="/veiculos/categoria-veiculo/nova-categoria" class="btn btn-primary btn-sm pull-left" id="add-categoria">
                                <b>+</b> Add nova Categoria
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped table-bordered" id="table-categoria-veiculo" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Descrição</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<style>
    #table-categoria-veiculo_length{
        display: none;
    }
</style>
<script>
    $(document).ready(function() {
        if ($("#table-categoria-veiculo").size() > 0) {
            $("#table-categoria-veiculo").dataTable({
                "ajax": {
                    url: '/veiculos/categoria-veiculo/get-categorias',
                    dataSrc: ''
                },
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Portuguese-Brasil.json"
                },
                "ordering": true,
                "bFilter": true,
                "bProcessing": true,
                "iDisplayLength": 8,
                "aoColumns": [
                    {
                        "data": "id",
                    },
                    {
                        "data": "descricao"
                    },
                    {
                        "data": "id",
                        mRender: function(data, type, row) {
                            var botoes = '<a href="/veiculos/categoria-veiculo/editar-categoria/id/' + data + '" id="editar-registro"  class="btn btn-primary btn-xs" data-title="Editar" ><span class="glyphicon glyphicon-pencil"></span></a>';
                            botoes += '<a data-id="' + data + '" id="deletar-registro" class="btn btn-danger btn-xs" data-title="Excluir" style="margin-left: 10px;"><span class="glyphicon glyphicon-trash"></span></a>';
                            return botoes;
                        },
                        "width": "60px",
                        "orderable": false
                    }
                ],
            });
        }
    });
</script>
<style>
    .dataTables_filter {
        margin-right: 10px;
        margin-top: -40px;
    }
</style>