<section class="content-header">
    <h1>
        Categoria de Veículo
        <small>Acompanhe aqui as categorias de veículos cadastrados</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/veiculos">Veículos</a></li>
        <li class="active">Categoria de Veículo</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="row">
                        <div class="col-md-6">
                            <a href="#" class="btn btn-primary btn-sm pull-left" id="add-categoria">
                                <b>+</b> Add nova Categoria</a>
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->form()->openTag($form); ?>
                            <div id="custom-search-input">
                                <div class="input-group">
                                    <?php echo $this->formRow($form->get('search')); ?> 
                                    <span class="input-group-btn">
                                        <button class="btn btn-info btn-sm" type="submit">
                                            <i class="glyphicon glyphicon-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                            <?php echo $this->form()->closeTag($form); ?>
                        </div>
                    </div>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover" id="table-categoria-veiculo">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Descrição</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Modal -->
<div class="modal fade" id="modal-categoria" tabindex="-1" role="dialog" aria-labelledby="contactLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="panel-title" id="contactLabel"><span class="glyphicon glyphicon-info-sign"></span>   Nova Categoria de Veículo</h4>
            </div>
            <?php echo $this->form()->openTag($formVeiculo); ?>
            <?php echo $this->formRow($formVeiculo->get('id')); ?>
            <div class="modal-body" style="padding: 5px;">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12" style="padding-bottom: 10px;">
                        <?php echo $this->formRow($formVeiculo->get('descricao')); ?>
                    </div>
                </div>
            </div>  
            <div class="modal-footer">
                <button type="button" class="btn btn-success btn-vote" id="salvar-categoria">Salvar</button>
                <button type="button" class="btn btn-danger btn-close" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <?php echo $this->form()->closeTag($formVeiculo); ?>
    </div>
</div>
<style>
    #table-categoria-veiculo_length{
        display: none;
    }
</style>
<script>
    $(document).ready(function () {
        $("#add-categoria").click(function () {
            $('#modal-categoria').modal('show')
        });
        $("#salvar-categoria").click(function (event) {
            $.ajax({
                type: "POST",
                url: '/veiculos/categoria-veiculo/nova-categoria',
                data: $("#categoria-veiculo").serialize(),
                success: function (data)
                {

                }
            });
        });
    });
    $(document).ready(function () {
        if ($("#table-categoria-veiculo").size() > 0) {
            $("#table-categoria-veiculo").dataTable({
                "ajax": {
                    url: '/veiculos/categoria-veiculo/get-categorias',
                    dataSrc: ''
                },
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Portuguese-Brasil.json"
                },
                //"paging": true,
                "ordering": true,
                //"info": true,
                "bFilter": false,
                //"pageLength": 9,
                "bProcessing": true,
                "iDisplayLength": 9,
                "aoColumns": [
                    {
                        "data": "id",
                    },
                    {
                        "data": "descricao"
                    },
                ],
            });
        }
    });
</script>