<section class="content-header">
    <h1>
        Adicionar Nova Categoria de Veículo
        <small>Cadastre aqui uma nova categoria de veículo</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/veiculos">Veículos</a></li>
        <li class="active">Nova Categoria de Veícculo</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formRow($form->get('id')); ?>
                    <div class="box-body">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('descricao')); ?> 
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-success">Salvar</button>
                        <a href="/veiculos/categoria-veiculo" class="btn btn-danger">Voltar</a>
                    </div>
                <?php echo $this->form()->closeTag($form); ?> 
            </div>
        </div>
    </div>
</section>