<section class="content-header">
    <h1>
        Modelo de Veículo
        <small>Acompanhe aqui os modelos de veículos cadastrados</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/veiculos">Veículos</a></li>
        <li class="active">Modelo de Veículo</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <div class="row">
                        <div class="col-md-6">
                            <a href="#" class="btn btn-primary btn-sm pull-left" id="add-modelo">
                                <b>+</b> Add novo Modelo
                            </a>
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->form()->openTag($form); ?>
                            <div id="custom-search-input">
                                <div class="input-group">
                                    <?php echo $this->formRow($form->get('search')); ?> 
                                    <span class="input-group-btn">
                                        <button class="btn btn-info btn-sm" type="submit">
                                            <i class="glyphicon glyphicon-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                            <?php echo $this->form()->closeTag($form); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped table-bordered" id="table-modelo-veiculo" width="100%">
                            <thead>
                                <tr>
                                    <th>Categoria</th>
                                    <th>Marca</th>
                                    <th>Modelo</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="modal-modelo" tabindex="-1" role="dialog" aria-labelledby="contactLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="panel-title" id="contactLabel"><span class="glyphicon glyphicon-info-sign"></span>   Novo Modelo de Veículo</h4>
            </div>
            <?php echo $this->form()->openTag($formModelo); ?>
            <?php echo $this->formRow($formModelo->get('id')); ?>
            <div class="modal-body" style="padding: 5px;">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4" style="padding-bottom: 10px;">
                        <?php echo $this->formRow($formModelo->get('categoria')); ?>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4" style="padding-bottom: 10px;">
                        <?php echo $this->formRow($formModelo->get('marca')); ?>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-" style="padding-bottom: 10px;">
                        <?php echo $this->formRow($formModelo->get('descricao')); ?>
                    </div>
                </div>
            </div>  
            <div class="modal-footer">
                <button type="button" class="btn btn-success btn-vote" id="salvar-modelo">Salvar</button>
                <button type="button" class="btn btn-danger btn-close" data-dismiss="modal">Fechar</button>
            </div>
        </div>
        <?php echo $this->form()->closeTag($formModelo); ?>
    </div>
</div>

<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title custom_align" id="Heading">Edição de Registro</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <input class="form-control " type="text" placeholder="Tiger Nixon">
                </div>
            </div>
            <div class="modal-footer ">
                <button type="button" class="btn btn-success btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Atualizar</button>
            </div>
        </div> 
    </div> 
</div>



<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title custom_align" id="Heading">Excluir Registro</h4>
            </div>
            <div class="modal-body">

                <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Você tem certeza que deseja excluir este registro?</div>

            </div>
            <div class="modal-footer ">
                <button type="button" class="btn btn-success" ><span class="glyphicon glyphicon-ok-sign"></span> Sim</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Não</button>
            </div>
        </div> 
    </div> 
</div>

<style>
    #table-modelo-veiculo_length{
        display: none;
    }
</style>
<script>
    $(document).ready(function () {
        $("#add-modelo").click(function () {
            $('#modal-modelo').modal('show')
        });
        $("#salvar-modelo").click(function (event) {
            $.ajax({
                type: "POST",
                url: '/veiculos/modelo-veiculo/novo-modelo',
                data: $("#modelo-veiculo").serialize(),
                success: function (data)
                {

                }
            });
        });
        $("#deletar-registro").click(function (event) {
            console.log(event);
        });
    });
    $(document).ready(function () {
        if ($("#table-modelo-veiculo").size() > 0) {
            $("#table-modelo-veiculo").dataTable({
                "ajax": {
                    url: '/veiculos/modelo-veiculo/get-modelos',
                    dataSrc: ''
                },
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Portuguese-Brasil.json"
                },
                "ordering": true,
                "bFilter": false,
                "bProcessing": true,
                "iDisplayLength": 8,
                "aoColumns": [
                    {
                        "data": "categoria"
                    },
                    {
                        "data": "marca"
                    },
                    {
                        "data": "descricao"
                    },
                    {
                        "data": "id",
                        mRender: function (data, type, row) {
                            var botoes = '<button data-id="' + data + '" id="editar-registro"  class="btn btn-primary btn-xs" data-title="Editar" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></button>';
                            botoes += '<button data-id="' + data + '" id="deletar-registro" class="btn btn-danger btn-xs" data-title="Excluir" style="margin-left: 10px;"><span class="glyphicon glyphicon-trash"></span></button>';
                            return botoes;
                        },
                        "width": "60px",
                        "orderable": false
                    }
                ],
            });
        }
    });
</script>