<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('On Frotas') ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="/plugins/iCheck/flat/blue.css">
        <!-- Morris chart -->
<!--        <link rel="stylesheet" href="/plugins/morris/morris.css">-->
        <!-- jvectormap -->
        <link rel="stylesheet" href="/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
        <!-- Date Picker -->
        <link rel="stylesheet" href="/plugins/datepicker/datepicker3.css">
        <!-- Daterange picker -->
        <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker-bs3.css">
        <!-- bootstrap wysihtml5 - text editor -->
        <link rel="stylesheet" href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body class="hold-transition skin-blue sidebar-mini">

        <div class="wrapper">
            <header class="main-header">
                <a href="/frotas" class="logo">
<!--                    <span class="logo-mini"><b>Frotas</b></span>-->
                    <span class="logo-lg"><b>OnFrotas</b></span>
                </a>
                <nav class="navbar navbar-static-top" role="navigation">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <aside class="main-sidebar">
                <section class="sidebar">
                    <ul class="sidebar-menu">
                        <li class="header">Menu de Navegação</li>
                        <li>
                            <a href="/frotas">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span> 
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-car"></i>
                                <span>Veículos</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="/veiculos/categoria-veiculo/index">
                                        <i class="fa fa-sticky-note-o"></i> Categorias de Veículos</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-tags"></i> Marcas de Veículos</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-tasks"></i> Modelos de Veículos</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </section>
            </aside>
            <div class="content-wrapper">
                <div id="messages">
                    <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
                        <div class="alert alert-success">
                            <?php foreach ($this->flashMessenger()->getSuccessMessages() as $msg) { ?>
                                <button type="button" class="close" data-dismiss="alert">×</button>    
                                <strong><?php echo $msg; ?></strong>
                            <?php } ?>
                        </div>
                    <?php } ?>


                    <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                        <div class="alert alert-danger">
                            <?php foreach ($this->flashMessenger()->getErrorMessages() as $msg) { ?>
                                <button type="button" class="close" data-dismiss="alert">×</button>    
                                <strong><?php echo $msg; ?></strong>
                            <?php } ?>
                        </div>
                    <?php } ?>

                    <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
                        <div class="alert alert-warning">
                            <?php foreach ($this->flashMessenger()->getInfoMessages() as $msg) { ?>
                                <button type="button" class="close" data-dismiss="alert">×</button>    
                                <strong ><?php echo $msg; ?></strong>
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>

                <?php echo $this->content; ?>

            </div>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Versão</b> 1.0
                </div>
                <strong>Copyright &copy; 2016 - OnFrotas</strong>
            </footer>
        </div>


        <?php echo $this->inlineScript() ?>
        <script src="/js/bootbox.js"></script>
        <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<!--        <script src="/plugins/morris/morris.min.js"></script>-->
        <script src="/plugins/sparkline/jquery.sparkline.min.js"></script>
        <script src="/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <script src="/plugins/knob/jquery.knob.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
        <script src="/plugins/daterangepicker/daterangepicker.js"></script>
        <script src="/plugins/datepicker/bootstrap-datepicker.js"></script>
        <script src="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
        <script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="/plugins/fastclick/fastclick.min.js"></script>
        <script src="/dist/js/app.min.js"></script>
<!--        <script src="/dist/js/pages/dashboard.js"></script>-->
        <script src="/dist/js/demo.js"></script>
        <script type="text/javascript" src="/js/DataTables.js"></script>
    </body>
</html>
